baseURL = "/"
title = "Suyoung Choi"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
relativeURLs = true
disableKinds = ["taxonomy", "term"]

[params]
  author = "Suyoung Choi"
  affiliation = "Department of Mathematics, Ajou University"
  email = "schoi [a] ajou.ac.kr"
  phone = "+82-31-219-3322"
  location = "Suwon, Republic of Korea"
  photo = "/images/2017-03-25.jpg"
